// Code generated by fabricator-generate-project-go
//
// Modifications in code regions will be lost during regeneration!
// region CODE_REGION(name)
module code.cestus.io/libs/buildinfo

go 1.17

// endregion

require (
	github.com/Scardiecat/svermaker v0.4.1
	github.com/google/wire v0.5.0
	github.com/onsi/ginkgo/v2 v2.0.0
	github.com/onsi/gomega v1.17.0
	gopkg.in/yaml.v3 v3.0.0-20210107192922-496545a6307b
)

require (
	github.com/blang/semver/v4 v4.0.0 // indirect
	github.com/sirupsen/logrus v1.8.1 // indirect
	golang.org/x/net v0.0.0-20210428140749-89ef3d95e781 // indirect
	golang.org/x/sys v0.0.0-20210423082822-04245dca01da // indirect
	golang.org/x/text v0.3.6 // indirect
	gopkg.in/yaml.v2 v2.4.0 // indirect
)
